let tableHeaders = [
    {field: 'id', translation: 'Табельный номер', visible: true, dataType: undefined},
    {field: 'firstName', translation: 'Имя', visible: true, dataType: 'string'},
    {field: 'secondName', translation: 'Фамилия', visible: true, dataType: 'string'},
    {field: 'salary', translation: 'Зарплата', visible: true, dataType: 'money'},
    {field: 'bonusInPercent', translation: 'Премия в процентах', visible: true, dataType: 'percent'},
    {field: 'bonusInMoney', translation: 'Премия в деньгах', visible: true, dataType: 'money'},
    {field: 'avatar', translation: 'Аватар', visible: true, dataType: undefined},
    {field: 'workExp', translation: 'Опыт', visible: true, dataType: 'number'},
    {field: 'gender', translation: 'Пол', visible: true, dataType: 'string'},
    {field: 'eyeColor', translation: 'Цвет глаз', visible: true, dataType: 'string'},
    {field: 'company', translation: 'Компания', visible: true, dataType: 'string'},
    {field: 'phone', translation: 'Телефон', visible: true, dataType: 'string'},
    {field: 'isActive', translation: 'Активен', visible: true, dataType: 'string'},
    {field: 'city', translation: 'Город', visible: true, dataType: 'string'},
    {field: 'country', translation: 'Страна', visible: true, dataType: 'string'},
    {field: 'countryCode', translation: 'Код страны', visible: true, dataType: 'number'},
    {field: 'email', translation: 'Почтовый ящик', visible: true, dataType: 'string'},
    {field: 'dateOfBirth', translation: 'Дата рождения', visible: true, dataType: undefined},
    {field: 'married', translation: 'В браке', visible: true, dataType: 'string'},
    {field: 'children', translation: 'Дети', visible: true, dataType: 'number'},
    {field: 'immigrant', translation: 'Иммигрант', visible: true, dataType: 'string'},
    {field: 'loyalty', translation: 'Лояльность', visible: true, dataType: 'number'},
    {field: 'power', translation: 'Сила', visible: true, dataType: 'number'},
    {field: 'stamina', translation: 'Выносливость', visible: true, dataType: 'number'},
    {field: 'speed', translation: 'Скорость', visible: true, dataType: 'number'},
    {field: 'jump', translation: 'Прыжок', visible: true, dataType: 'number'},
    {field: 'accuracy', translation: 'Точность', visible: true, dataType: 'number'},
    {field: 'attribute1', translation: 'Атрибут 1', visible: true, dataType: 'number'},
    {field: 'attribute2', translation: 'Атрибут 2', visible: true, dataType: 'number'},
    {field: 'attribute3', translation: 'Атрибут 3', visible: true, dataType: 'number'},
    {field: 'attribute4', translation: 'Атрибут 4', visible: true, dataType: 'number'},
    {field: 'attribute5', translation: 'Атрибут 5', visible: true, dataType: 'number'},
    {field: 'attribute6', translation: 'Атрибут 6', visible: true, dataType: 'number'},
    {field: 'attribute7', translation: 'Атрибут 7', visible: true, dataType: 'number'},
    {field: 'attribute8', translation: 'Атрибут 8', visible: true, dataType: 'number'},
    {field: 'attribute9', translation: 'Атрибут 9', visible: true, dataType: 'number'},
    {field: 'attribute10', translation: 'Атрибут 10', visible: true, dataType: 'number'},
    {field: 'attribute11', translation: 'Атрибут 11', visible: true, dataType: 'number'},
    {field: 'attribute12', translation: 'Атрибут 12', visible: true, dataType: 'number'},
    {field: 'attribute13', translation: 'Атрибут 13', visible: true, dataType: 'number'},
    {field: 'attribute14', translation: 'Атрибут 14', visible: true, dataType: 'number'},
    {field: 'attribute15', translation: 'Атрибут 15', visible: true, dataType: 'number'},
]
export default tableHeaders